//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace СтудентП31.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class СтудентП31Entities : DbContext
    {
        public СтудентП31Entities()
            : base("name=СтудентП31Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Группа> Группа { get; set; }
        public virtual DbSet<Предмет> Предмет { get; set; }
        public virtual DbSet<Преподаватель> Преподаватель { get; set; }
        public virtual DbSet<РезультатЭкзамена> РезультатЭкзамена { get; set; }
        public virtual DbSet<Специальность> Специальность { get; set; }
        public virtual DbSet<Студент> Студент { get; set; }
        public virtual DbSet<ЭкзаменационнаяВедомость> ЭкзаменационнаяВедомость { get; set; }
    }
}
