//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace СтудентП31.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Группа
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Группа()
        {
            this.Студент = new HashSet<Студент>();
            this.ЭкзаменационнаяВедомость = new HashSet<ЭкзаменационнаяВедомость>();
        }
    
        public int КодГруппы { get; set; }
        public string НазваниеГруппы { get; set; }
        public int Специальность { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Студент> Студент { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭкзаменационнаяВедомость> ЭкзаменационнаяВедомость { get; set; }
        public virtual Специальность Специальность1 { get; set; }
    }
}
