//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace СтудентП31.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Студент()
        {
            this.РезультатЭкзамена = new HashSet<РезультатЭкзамена>();
        }
    
        public int КодСтудента { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public int ГруппаКод { get; set; }
        public Nullable<System.DateTime> ДатаРождения { get; set; }
    
        public virtual Группа Группа { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РезультатЭкзамена> РезультатЭкзамена { get; set; }
    }
}
