//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace СтудентП31.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЭкзаменационнаяВедомость
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ЭкзаменационнаяВедомость()
        {
            this.РезультатЭкзамена = new HashSet<РезультатЭкзамена>();
        }
    
        public int КодВедомости { get; set; }
        public Nullable<int> ГруппыКод { get; set; }
        public Nullable<int> ПредметаКод { get; set; }
        public Nullable<int> ПреподавателяКод { get; set; }
        public string Кабинет { get; set; }
        public Nullable<System.DateTime> ДатаЭкзамена { get; set; }
    
        public virtual Группа Группа { get; set; }
        public virtual Предмет Предмет { get; set; }
        public virtual Преподаватель Преподаватель { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РезультатЭкзамена> РезультатЭкзамена { get; set; }
    }
}
